# Generated by Django 4.1.7 on 2023-04-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intro", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="intros",
            name="joined_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="intros",
            name="phone",
            field=models.IntegerField(null=True),
        ),
    ]
